// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mail.proto

package mailingService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailingService_CreateEmail_FullMethodName       = "/proto.MailingService/CreateEmail"
	MailingService_GetEmail_FullMethodName          = "/proto.MailingService/GetEmail"
	MailingService_UpdateEmail_FullMethodName       = "/proto.MailingService/UpdateEmail"
	MailingService_DeleteEmail_FullMethodName       = "/proto.MailingService/DeleteEmail"
	MailingService_GetEmailPaginated_FullMethodName = "/proto.MailingService/GetEmailPaginated"
)

// MailingServiceClient is the client API for MailingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service definition to run code on server
type MailingServiceClient interface {
	CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	GetEmail(ctx context.Context, in *GetEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	DeleteEmail(ctx context.Context, in *DeleteEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	GetEmailPaginated(ctx context.Context, in *GetEmailPaginatedRequest, opts ...grpc.CallOption) (*GetEmailPaginatedResponse, error)
}

type mailingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailingServiceClient(cc grpc.ClientConnInterface) MailingServiceClient {
	return &mailingServiceClient{cc}
}

func (c *mailingServiceClient) CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, MailingService_CreateEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailingServiceClient) GetEmail(ctx context.Context, in *GetEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, MailingService_GetEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailingServiceClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, MailingService_UpdateEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailingServiceClient) DeleteEmail(ctx context.Context, in *DeleteEmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, MailingService_DeleteEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailingServiceClient) GetEmailPaginated(ctx context.Context, in *GetEmailPaginatedRequest, opts ...grpc.CallOption) (*GetEmailPaginatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailPaginatedResponse)
	err := c.cc.Invoke(ctx, MailingService_GetEmailPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailingServiceServer is the server API for MailingService service.
// All implementations must embed UnimplementedMailingServiceServer
// for forward compatibility.
//
// service definition to run code on server
type MailingServiceServer interface {
	CreateEmail(context.Context, *CreateEmailRequest) (*EmailResponse, error)
	GetEmail(context.Context, *GetEmailRequest) (*EmailResponse, error)
	UpdateEmail(context.Context, *UpdateEmailRequest) (*EmailResponse, error)
	DeleteEmail(context.Context, *DeleteEmailRequest) (*EmailResponse, error)
	GetEmailPaginated(context.Context, *GetEmailPaginatedRequest) (*GetEmailPaginatedResponse, error)
	mustEmbedUnimplementedMailingServiceServer()
}

// UnimplementedMailingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailingServiceServer struct{}

func (UnimplementedMailingServiceServer) CreateEmail(context.Context, *CreateEmailRequest) (*EmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmail not implemented")
}
func (UnimplementedMailingServiceServer) GetEmail(context.Context, *GetEmailRequest) (*EmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmail not implemented")
}
func (UnimplementedMailingServiceServer) UpdateEmail(context.Context, *UpdateEmailRequest) (*EmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEmail not implemented")
}
func (UnimplementedMailingServiceServer) DeleteEmail(context.Context, *DeleteEmailRequest) (*EmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEmail not implemented")
}
func (UnimplementedMailingServiceServer) GetEmailPaginated(context.Context, *GetEmailPaginatedRequest) (*GetEmailPaginatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailPaginated not implemented")
}
func (UnimplementedMailingServiceServer) mustEmbedUnimplementedMailingServiceServer() {}
func (UnimplementedMailingServiceServer) testEmbeddedByValue()                        {}

// UnsafeMailingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailingServiceServer will
// result in compilation errors.
type UnsafeMailingServiceServer interface {
	mustEmbedUnimplementedMailingServiceServer()
}

func RegisterMailingServiceServer(s grpc.ServiceRegistrar, srv MailingServiceServer) {
	// If the following call panics, it indicates UnimplementedMailingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailingService_ServiceDesc, srv)
}

func _MailingService_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailingServiceServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailingService_CreateEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailingServiceServer).CreateEmail(ctx, req.(*CreateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailingService_GetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailingServiceServer).GetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailingService_GetEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailingServiceServer).GetEmail(ctx, req.(*GetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailingService_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailingServiceServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailingService_UpdateEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailingServiceServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailingService_DeleteEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailingServiceServer).DeleteEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailingService_DeleteEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailingServiceServer).DeleteEmail(ctx, req.(*DeleteEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailingService_GetEmailPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailPaginatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailingServiceServer).GetEmailPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailingService_GetEmailPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailingServiceServer).GetEmailPaginated(ctx, req.(*GetEmailPaginatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailingService_ServiceDesc is the grpc.ServiceDesc for MailingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MailingService",
	HandlerType: (*MailingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmail",
			Handler:    _MailingService_CreateEmail_Handler,
		},
		{
			MethodName: "GetEmail",
			Handler:    _MailingService_GetEmail_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _MailingService_UpdateEmail_Handler,
		},
		{
			MethodName: "DeleteEmail",
			Handler:    _MailingService_DeleteEmail_Handler,
		},
		{
			MethodName: "GetEmailPaginated",
			Handler:    _MailingService_GetEmailPaginated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
